# themes.py - Catppuccin color themes for Scryptian

THEMES = {
    "mocha": {
        "name": "Catppuccin Mocha",
        "crust": "#11111b",
        "mantle": "#181825",
        "base": "#1e1e2e",
        "surface0": "#313244",
        "surface1": "#45475a",
        "surface2": "#585b70",
        "overlay0": "#6c7086",
        "overlay1": "#7f849c",
        "overlay2": "#9399b2",
        "subtext0": "#a6adc8",
        "subtext1": "#bac2de",
        "text": "#cdd6f4",
        "lavender": "#b4befe",
        "blue": "#89b4fa",
        "sapphire": "#74c7ec",
        "sky": "#89dceb",
        "teal": "#94e2d5",
        "green": "#a6e3a1",
        "yellow": "#f9e2af",
        "peach": "#fab387",
        "maroon": "#eba0ac",
        "red": "#f38ba8",
        "mauve": "#cba6f7",
        "pink": "#f5c2e7",
        "flamingo": "#f2cdcd",
        "rosewater": "#f5e0dc",
    },
    "macchiato": {
        "name": "Catppuccin Macchiato",
        "crust": "#181926",
        "mantle": "#1e2030",
        "base": "#24273a",
        "surface0": "#363a4f",
        "surface1": "#494d64",
        "surface2": "#5b6078",
        "overlay0": "#6e738d",
        "overlay1": "#8087a2",
        "overlay2": "#939ab7",
        "subtext0": "#a5adcb",
        "subtext1": "#b8c0e0",
        "text": "#cad3f5",
        "lavender": "#b7bdf8",
        "blue": "#8aadf4",
        "sapphire": "#7dc4e4",
        "sky": "#91d7e3",
        "teal": "#8bd5ca",
        "green": "#a6da95",
        "yellow": "#eed49f",
        "peach": "#f5a97f",
        "maroon": "#ee99a0",
        "red": "#ed8796",
        "mauve": "#c6a0f6",
        "pink": "#f5bde6",
        "flamingo": "#f0c6c6",
        "rosewater": "#f4dbd6",
    },
    "frappe": {
        "name": "Catppuccin Frappe",
        "crust": "#1e2030",
        "mantle": "#232634",
        "base": "#292c3c",
        "surface0": "#303446",
        "surface1": "#414559",
        "surface2": "#51576d",
        "overlay0": "#626880",
        "overlay1": "#737994",
        "overlay2": "#838ba7",
        "subtext0": "#949cbb",
        "subtext1": "#a5adce",
        "text": "#c6d0f5",
        "lavender": "#babbf1",
        "blue": "#8caaee",
        "sapphire": "#85c1dc",
        "sky": "#99d1db",
        "teal": "#81c8be",
        "green": "#a6d189",
        "yellow": "#e5c890",
        "peach": "#ef9f76",
        "maroon": "#ea999c",
        "red": "#e78284",
        "mauve": "#ca9ee6",
        "pink": "#f4b8e4",
        "flamingo": "#f2d5cf",
        "rosewater": "#f2d5cf",
    },
    "latte": {
        "name": "Catppuccin Latte",
        "crust": "#dce0e8",
        "mantle": "#e6e9ef",
        "base": "#eff1f5",
        "surface0": "#ccd0da",
        "surface1": "#bcc0cc",
        "surface2": "#acb0be",
        "overlay0": "#9ca0b0",
        "overlay1": "#8c8fa1",
        "overlay2": "#7c7f93",
        "subtext0": "#6c6f85",
        "subtext1": "#5c5f77",
        "text": "#4c4f69",
        "lavender": "#7287fd",
        "blue": "#1e66f5",
        "sapphire": "#209fb5",
        "sky": "#04a5e5",
        "teal": "#179299",
        "green": "#40a02b",
        "yellow": "#df8e1d",
        "peach": "#fe640b",
        "maroon": "#e64553",
        "red": "#d20f39",
        "mauve": "#8839ef",
        "pink": "#ea76cb",
        "flamingo": "#dd7878",
        "rosewater": "#dc8a78",
    },
}

SYNTAX_COLORS = {
    "Keyword": "mauve",
    "Keyword.Namespace": "mauve",
    "Keyword.Type": "yellow",
    "Keyword.Constant": "peach",
    "Name.Function": "blue",
    "Name.Class": "yellow",
    "Name.Decorator": "pink",
    "Name.Builtin": "red",
    "Name.Builtin.Pseudo": "red",
    "String": "green",
    "String.Affix": "green",
    "String.Escape": "peach",
    "Number": "peach",
    "Number.Float": "peach",
    "Comment": "overlay0",
    "Comment.Multiline": "overlay0",
    "Comment.Single": "overlay0",
    "Operator": "sky",
    "Operator.Word": "mauve",
    "Punctuation": "subtext1",
    "Name.Variable": "text",
    "Name.Tag": "red",
    "Name.Attribute": "yellow",
    "Literal": "teal",
    "Literal.Date": "teal",
    "Generic.Heading": "blue",
    "Generic.Subheading": "blue",
    "Generic.Deleted": "red",
    "Generic.Inserted": "green",
    "Generic.Error": "red",
}


def get_theme(name):
    return THEMES.get(name, THEMES["mocha"])


def get_syntax_colors(theme):
    return {token: theme[color_key] for token, color_key in SYNTAX_COLORS.items()}


AVAILABLE_THEMES = [(key, t["name"]) for key, t in THEMES.items()]
